export const BUFFABLE_STATS = [
  { value: "attack_percent", label: "ATK%" },
  { value: "flat_attack", label: "Flat ATK" },
  { value: "hp_percent", label: "HP%" },
  { value: "base_def", label: "Base DEF" },
  { value: "def_percent", label: "DEF%" },
  { value: "flat_def", label: "Flat DEF" },
  { value: "elemental_mastery", label: "Elem. Mastery" },
  { value: "energy_recharge", label: "Energy Recharge%" },
  { value: "crit_rate", label: "Crit Rate%" },
  { value: "crit_damage", label: "Crit Damage%" },
  { value: "damage_bonus_elemental", label: "Elem. DMG Bonus%" },
  { value: "damage_bonus_talent", label: "Talent DMG Bonus%" },
  { value: "damage_bonus_all", label: "Other DMG Bonus%" },
  { value: "melt_bonus", label: "Melt Bonus%" },
  { value: "base_damage_bonus", label: "Base DMG Bonus" },
  { value: "defense_shred", label: "Defense Shred%" },
  { value: "quicken_bonus", label: "Quicken Bonus%" },
  { value: "defense_reduction", label: "Defense Reduction%" },
];
