export const STAT_LABEL = {
  level: "Level",
  element: "Element",
  base_attack: "Base Attack",
  attack_percent: "ATK%",
  flat_attack: "Flat ATK",
  base_hp: "Base HP",
  hp_percent: "HP%",
  flat_hp: "Flat HP",
  base_def: "Base DEF",
  def_percent: "DEF%",
  flat_def: "Flat DEF",
  elemental_mastery: "Elem. Mastery",
  energy_recharge: "Energy Recharge%",
  crit_rate: "Crit Rate%",
  crit_damage: "Crit Damage%",
  damage_bonus_elemental: "Elem. DMG Bonus%",
  damage_bonus_talent: "Talent DMG Bonus%",
  damage_bonus_all: "Other DMG Bonus%",
  melt_bonus: "Melt Bonus%",
  base_damage_bonus: "Base DMG Bonus",
  defense_shred: "Defense Shred%",
  quicken_bonus: "Quicken Bonus%",
  resistance_to_damage_element: "Elemental Resistance%",
  defense_percent_dropped: "Defense Dropped%",
};
